# Bike sales EDA part 2

In [1]:
import pandas as pd

df = pd.read_csv("../../data/Sales.csv", index_col=0, parse_dates=True)
df.head()

,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
Date,,,,,,,,,,,,,,,,,
2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

### dates

In [ ]:
# mutate existing dataframe
# same as df = df.sort_index()
df.sort_index(inplace=True)

In [11]:
df.loc["2013-01-01":"2013-01-03"]

,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
Date,,,,,,,,,,,,,,,,,
2013-01-01,1,January,2013,29,Young Adults (25-34),F,United States,Florida,Bikes,Road Bikes,"Road-650 Red, 62",1,487,783,257,487,744
2013-01-01,1,January,2013,29,Young Adults (25-34),M,United States,Oregon,Bikes,Road Bikes,"Road-650 Black, 44",1,487,783,186,487,673
2013-01-01,1,January,2013,19,Youth (<25),F,United States,Washington,Bikes,Road Bikes,"Road-150 Red, 48",1,2171,3578,620,2171,2791
2013-01-01,1,January,2013,53,Adults (35-64),F,France,Seine (Paris),Bikes,Road Bikes,"Road-250 Black, 44",1,1555,2443,448,1555,2003
2013-01-01,1,January,2013,42,Adults (35-64),M,Australia,Queensland,Bikes,Road Bikes,"Road-350-W Yellow, 48",1,1083,1701,346,1083,1429
2013-01-01,1,January,2013,36,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Silver, 46",1,1266,2320,1008,1266,2274
2013-01-01,1,January,2013,27,Young Adults (25-34),F,Australia,New South Wales,Bikes,Road Bikes,"Road-550-W Yellow, 48",1,713,1120,261,713,974
2013-01-01,1,January,2013,37,Adults (35-64),F,Germany,Hamburg,Bikes,Road Bikes,"Road-250 Black, 48",1,1555,2443,717,1555,2272
2013-01-02,2,January,2013,37,Adults (35-64),F,United Kingdom,England,Bikes,Road Bikes,"Road-350-W Yellow, 48",1,1083,1701,550,1083,1633
2013-01-02,2,January,2013,29,Young Adults (25-34),M,Australia,New South Wales,Bikes,Road Bikes,"Road-750 Black, 44",1,344,540,126,344,470
2013-01-02,2,January,2013,25,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-200 Silver, 46",1,1266,2320,752,1266,2018
2013-01-02,2,January,2013,29,Young Adults (25-34),F,Australia,New South Wales,Bikes,Road Bikes,"Road-150 Red, 62",1,2171,3578,942,2171,3113
2013-01-02,2,January,2013,30,Young Adults (25-34),M,United Kingdom,England,Bikes,Road Bikes,"Road-750 Black, 48",1,344,540,174,344,518
2013-01-02,2,January,2013,30,Young Adults (25-34),M,France,Essonne,Bikes,Road Bikes,"Road-150 Red, 48",1,2171,3578,1264,2171,3435
2013-01-02,2,January,2013,30,Young Adults (25-34),M,United Kingdom,England,Bikes,Road Bikes,"Road-750 Black, 48",1,344,540,174,344,518
2013-01-02,2,January,2013,28,Young Adults (25-34),M,United States,California,Bikes,Road Bikes,"Road-150 Red, 62",1,2171,3578,1335,2171,3506
2013-01-02,2,January,2013,25,Young Adults (25-34),M,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-200 Black, 38",1,1252,2295,745,1252,1997
2013-01-02,2,January,2013,38,Adults (35-64),M,Germany,Nordrhein-Westfalen,Bikes,Road Bikes,"Road-350-W Yellow, 44",1,1083,1701,397,1083,1480
2013-01-02,2,January,2013,27,Young Adults (25-34),M,Australia,Queensland,Bikes,Mountain Bikes,"Mountain-200 Silver, 46",1,1266,2320,683,1266,1949
2013-01-02,2,January,2013,27,Young Adults (25-34),F,Germany,Hessen,Bikes,Mountain Bikes,"Mountain-200 Black, 42",1,1252,2295,882,1252,2134
2013-01-03,3,January,2013,30,Young Adults (25-34),F,Australia,Victoria,Bikes,Mountain Bikes,"Mountain-200 Black, 38",1,1252,2295,561,1252,1813
2013-01-03,3,January,2013,23,Youth (<25),M,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-200 Silver, 38",1,1266,2320,752,1266,2018
2013-01-03,3,January,2013,40,Adults (35-64),F,Australia,Queensland,Bikes,Road Bikes,"Road-350-W Yellow, 40",1,1083,1701,346,1083,1429
2013-01-03,3,January,2013,30,Young Adults (25-34),F,United States,California,Bikes,Road Bikes,"Road-650 Black, 58",1,487,783,280,487,767
2013-01-03,3,January,2013,25,Young Adults (25-34),M,United Kingdom,England,Bikes,Road Bikes,"Road-250 Red, 58",1,1555,2443,790,1555,2345
2013-01-03,3,January,2013,41,Adults (35-64),M,Canada,British Columbia,Bikes,Road Bikes,"Road-150 Red, 48",1,2171,3578,1371,2171,3542
2013-01-03,3,January,2013,29,Young Adults (25-34),F,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1,1266,2320,961,1266,2227